# Generated by Django 3.2.5 on 2021-07-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='dese',
            new_name='desc',
        ),
    ]
